blank_issues_enabled: false
contact_links:
  - name: 没有 GitHub 账号? 不会使用 GitHub?
    url: https://qm.qq.com/cgi-bin/qm/qr?k=2bbciWAJ-GEzNtDq2NuSI5MMh7s10a9w&jump_from=webapi
    about: 点击右侧按钮加入未来城官方QQ群
